### ISSUE TITLE
Screenshots not showing up in report because filenames are too long

### ISSUE THREAD

**Issue by raghavsachdev** [BelAn97/mochawesome-screenshots#13]
I am seeing an issue where my reports don't show the screenshots.  When I dug in, it looks like the screenshot names are so long, they are getting truncated by OS X but the report is looking for the full filename. 

For example, the source is loading: ./screenshots/48123_create_a_collection_as_a_logged_in_agent_create_collection_ui_tests_asserts_that_invalid_character_values_are_rejected_by_the_ui.png

But the screenshots folder has this file: 48123__regression___agent___boards___collections_create_a_collection_as_a_logged_in_agent_create_collection_ui_tests_asserts_that_inva.png

Also note how the filenames have double underscores around the mocha tags, but the HTML doesn't expect them.

Can we have an option to just have unique numbers as the names of the screenshots?

**Comment by BelAn97** [comment]
Done. You can use "shortScrFileNames: true" option for short names

**Comment by ndiaz-candido** [comment]
Hi @BelAn97, I have enabled the `shortScrFileNames` flag to get short names but it seems is loosing the image references. 

In my case the source is looking for: `screenshots/_and_when_opens_the_share_modal_to_add_the_asset_to_the_public_portal_and_when_logs_out_and_goes_to_the_public_portal_and_searches_the_asset_then_he_should_be_able_to_.png`
But the screenshot was saved as:
`screenshots/_given_an_authenticated_user_when_he_publishes_an_oas_asset_and_when_opens_the_share_modal_to_add_the_asset_to_the_public_portal_and_when_logs_out_and_goes_to_the_publ.png`
Not sure if the feature is working for me or something wrong is happening. I have installed the last version `1.5.7` where you delivered the feature.

@raghavsachdev did the feature work for you?

Thanks in advance!

**Comment by BelAn97** [comment]
Hi @ndiaz-candido, I'll check it at mac os x a little bit later.

**Comment by raghavsachdev** [comment]
@ndiaz-candido @BelAn97 I just installed this on another mac and added the shortScrFileNames: true option but I am still seeing the same problem. The report is looking for a screenshot with a filename that was cut off by OS X.

**Comment by BelAn97** [comment]
Hi @ndiaz-candido, @raghavsachdev. I've check it at my mac os x - all worked fine. 
I've made some changes that could be fix your issues. Please, try version 1.5.8.

**Comment by raghavsachdev** [comment]
Looks good to me! Thanks @BelAn97
